### ISSUE TITLE
Not compatible with latest version of Python-Telegram-Bot

### ISSUE THREAD

**Issue by OzzyCallooh** [OzzyCallooh/DemonButlerBot#2]
Looks like `handle_error` (among other functions) need to handle new params.  The bot works with `python-telegram-bot==10.1.0`

```
INFO:apscheduler.scheduler:Scheduler started
ERROR:telegram.ext.dispatcher:An uncaught error was raised while handling the error.
Traceback (most recent call last):
  File "/usr/local/lib/DemonButlerBot/.venv/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 432, in process_update
    handler.handle_update(update, self, check, context)
  File "/usr/local/lib/DemonButlerBot/.venv/lib/python3.6/site-packages/telegram/ext/handler.py", line 156, in handle_update
    return self.callback(update, context)
  File "/usr/local/lib/DemonButlerBot/src/cmdlogging.py", line 7, in wrapped
    msg = '[user:{userid}{username},chat:{chatid}]: ' + update.message.text
AttributeError: 'CallbackContext' object has no attribute 'message'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/DemonButlerBot/.venv/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 448, in process_update
    self.dispatch_error(update, exc)
  File "/usr/local/lib/DemonButlerBot/.venv/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 658, in dispatch_error
    callback(update, context)
TypeError: handle_error() missing 1 required positional argument: 'error'
ERROR:telegram.ext.dispatcher:An uncaught error was raised while handling the error.
Traceback (most recent call last):
  File "/usr/local/lib/DemonButlerBot/.venv/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 432, in process_update
    handler.handle_update(update, self, check, context)
  File "/usr/local/lib/DemonButlerBot/.venv/lib/python3.6/site-packages/telegram/ext/handler.py", line 156, in handle_update
    return self.callback(update, context)
  File "/usr/local/lib/DemonButlerBot/src/cmdlogging.py", line 7, in wrapped
    msg = '[user:{userid}{username},chat:{chatid}]: ' + update.message.text
AttributeError: 'CallbackContext' object has no attribute 'message'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/DemonButlerBot/.venv/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 448, in process_update
    self.dispatch_error(update, exc)
  File "/usr/local/lib/DemonButlerBot/.venv/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 658, in dispatch_error
    callback(update, context)
TypeError: handle_error() missing 1 required positional argument: 'error'
```

**Comment by OzzyCallooh** [comment]
Fixed in ae5ab63
